spring:
  datasource:
    username: root
    password: gdutelc2021sql
    url: jdbc:mysql://104.160.18.224:3306/db_sign_up?characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 120000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  redis:
    database: 0
    host: 104.160.18.224
    port: 6379
    password: gdutelc2021redis
    connect-timeout: 1000
    jedis:
      pool:
        max-active: 10
        max-idle: 8
        min-idle: 0
        max-wait: -1


  cache:
    type: redis
    redis:
      #是否缓存空值，防止缓存穿透
      cache-null-values: true
      #缓存过期时间（ms）
      time-to-live: 100000
  kafka:
    bootstrap-servers: 192.168.0.2:9092
    producer:
      retries: 0
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      bootstrap-servers: 192.168.0.2:9092
      group-id: user
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    template:
      default-topic: phone


mybatis:
  mapper-locations: classpath:com/gdutelc/snp/dao/*.xml:com.gdutelc.snp.entity
  type-aliases-package: com.gdutelc.snp.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

config:
  aes:
    key: gdutelc2021aes

  register:
    appid: wx5b6dd7febf70b30b
    secret: 6667dcbaecf63bd4787463b8303abdf7
  jwt:
    user:
      salt: gdutelc2021user
      expire: 36000
      header: jwt

    userweb:
      salt: gdutelc2021userweb
      expire: 36000
      header: jwt
    admin:
      salt: gdutelc2021admin
      expire: 36000
      header: jwt




server:
  port: 10080
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure:
            logging: info


